service: order-finder-service

provider:
  name: aws
  runtime: provided.al2023
  region: us-east-1
  environment:
    GOOGLE_MAPS_API_KEY: ${env:GOOGLE_MAPS_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:us-east-1:*:table/Orders

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        AttributeDefinitions:
          - AttributeName: orderID
            AttributeType: S
        KeySchema:
          - AttributeName: orderID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  order:
    handler: bootstrap
    events:
      - http:
          path: order
          method: post
          cors: true  
      - http:
          path: order
          method: get
          cors: true
  listOrders:
    handler: bootstrap
    events:
      - http:
          path: orders
          method: get

plugins:
  - serverless-go-plugin
